language: ruby
cache: bundler
branches:
  only:
  - master
install: bundle install
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
deploy:
  provider: pages
  local-dir: ./site
  target-branch: dist
  skip_cleanup: true
  github_token: $TRAVIS_GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
after_success: s3_website push