language: ruby
cache:
  directories:
  - vendor/bundle
branches:
  only:
  - release
install: bundle install
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
deploy:
  - provider: s3
    access_key_id: $S3_ACCESS_KEY_ID
    secret_access_key: $S3_SECRET_KEY
    local_dir: ./site/assets
    bucket: "assets.ahiravan.dev"
    skip_cleanup: true
    region: "ap-south-1"
    upload-dir: assets
    on:
      branch: release
  - provider: pages
    local-dir: ./site
    target-branch: master
    skip_cleanup: true
    github_token: $TRAVIS_GH_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    on:
      branch: release

