language: ruby
cache: bundler
branches:
  only:
  - release
  - master
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
deploy:
  provider: pages
  local-dir: ./site
  target-branch: master
  skip_cleanup: true
  github_token: $TRAVIS_GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: release