# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
 - index.md
 - work.md
 - blog.md
 - musings.md


style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

collections:
  - works
