# Example Site settings

#google_analytics: UA-NNNNNNNN-N
include:
  - _main

header_pages:
 - _main/index.md
 - _main/work.md
 - _main/blog.md
 - _main/more.md


style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

collections:
  - works

sass:
    style: compressed